name: build

on: [ push ]

jobs:
  setup:
    runs-on: ubuntu-latest
    container: furetur/plugin-utilities

    steps:
      - uses: actions/checkout@v2

      # Cache Gradle dependencies
      # Cache Gradle Wrapper
      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-



  build:
    needs: setup
    runs-on: ubuntu-latest
    container: furetur/plugin-utilities

    steps:
      - uses: actions/checkout@v2

      - name: Build the project
        run: ./gradlew build

      - name: Upload Test Report
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: test-report
          path: |
            **/build/reports/tests/**/*

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Check if the examples project works correctly with the current version as a Gradle dependency
        run: |
          export PLUGIN_UTILITIES_BRANCH=${{ steps.extract_branch.outputs.branch }}
          ./examples/gradlew build
